
name: Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: gradle -Pversion=${{github.event.release.tag_name}} build

    - name: Publish to GitHub Packages
      run: gradle -Pversion=${{github.event.release.tag_name}} publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy-test:
    needs:
      - build
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "deploying version ${{ github.event.release.tag_name }} using key ${{secrets.DEPLOY_KEY}}"

  it-test:
    needs:
      - deploy-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "running tests on environment test"

  deploy-production:
    needs:
      - it-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "deploying version ${{ github.event.release.tag_name }} using key ${{secrets.DEPLOY_KEY}}"

  it-production:
    needs:
      - deploy-production
    runs-on: ubuntu-latest
    steps:
      - run: echo "running tests on environment production"

