
name: Java CI with Gradle

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --info -Pversion=2.0 cleanTest build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.19
        if: always()
        with:
          files: build/test-results/test/*.xml

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying"

  integration-test:
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "running tests"


