name: Java CI with reusable Build

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build:
    uses: ralfstuckert/workflow-demo/.github/workflows/resuable_build.yml@main        
        
  deploy:
   needs: 
    - build
   runs-on: ubuntu-latest
   environment: develop
   steps:
     - run: echo "deploying version ${{needs.build.outputs.jar-version}} using secret using key ${{secrets.DEPLOY_KEY}}"

  integration-test:
    needs:
     - deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "running tests"
