name: Expression must not start with '!' (not)

on:
  workflow_dispatch:
  
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
    - name: echo if true
      run: echo "yeehaw"
      if: ${{ !false }}

